version: '3.7'

services:
  django:
    container_name: back
    build: 
      context: ./django_back
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_back/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./django_back/.env.dev
    depends_on:
      - postgres

  postgres:
    container_name: db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=me
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
