version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    # restart: always
    # privileged: true
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_dbData:/var/lib/postgresql/data

volumes:
  postgres_dbData:
