version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "1337:80"
    depends_on:
      - django

  django:
    container_name: django_react
    build: 
      context: ./django_react
      dockerfile: Dockerfile.prod
    command: gunicorn django_react.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - ./django_react/.env.prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
