version: '3.7'

services:
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - react

  react:
    container_name: front
    build:
      context: ./react_front
      dockerfile: Dockerfile
    volumes:
      - ./react_front/node_modules/:/usr/src/app/node_modules/
      - ./react_front/src:/usr/src/app/src/
    ports:
      - "3000:3000"
    depends_on:
      - django

  django:
    container_name: back
    build: 
      context: ./django_back
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_back/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

  postgres:
    container_name: db
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
