version: '3.7'

services:
  django:
    build: 
      context: ./django_react
      dockerfile: Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./django_react/.env.prod
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    env_file:
      - ./.env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
