# Generated by Django 2.0.6 on 2020-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rdv', '0002_auto_20200905_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'status 1'), ('2', 'status 2'), ('3', 'status 3')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='prefecture',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('C', 'Close')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('1', 'status 1'), ('2', 'status 2'), ('3', 'status 3')], default='1', max_length=1),
        ),
    ]
