# Generated by Django 2.0.6 on 2020-09-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rdv', '0003_auto_20200905_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='link',
        ),
    ]
