# Generated by Django 2.0.6 on 2020-09-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rdv', '0004_auto_20200905_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Product_Prefecture_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_prefecture_relationship', to='Rdv.Order')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_prefecture_relationship', to='Rdv.Prefecture')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='prefecture',
        ),
        migrations.RemoveField(
            model_name='order_product',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.ManyToManyField(through='Rdv.Order_Product_Prefecture_Relationship', to='Rdv.Order'),
        ),
        migrations.DeleteModel(
            name='Order_Product',
        ),
        migrations.AddField(
            model_name='order_product_prefecture_relationship',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_prefecture_relationship', to='Rdv.Product'),
        ),
    ]
